In [17]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8,9,0])
array2 = np.random.randint(10,size=(10))
print(array1)
print(array2)

[1 2 3 4 5 6 7 8 9 0]
[9 7 8 7 1 6 9 7 6 4]


In [18]:
np.intersect1d(array1,array2)

array([1, 4, 6, 7, 8, 9])